<a href="https://colab.research.google.com/github/KirilPal/Laboratory_work_numerical_methods-/blob/main/%D0%9B%D0%A0_4_%D0%9F%D0%B0%D0%BB%D0%B0%D0%BC%D0%B0%D1%80%D1%87%D1%83%D0%BA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Паламарчук Кіріл
Лабораторна робота №4
Варіант 22
Група 2-8

## 1. Знайти матрицю С = 𝐴𝐵 − 𝐵𝐴:
## 1) 𝐴 = [1; 2] [4; −1], 𝐵 = [2; −3] [−4; 1];

In [2]:
import numpy as np

a = np.matrix([[1, 2], [4, -1]])
b = np.matrix([[2, -3], [-4, 1]])

c = np.dot(a, b) - np.dot(b, a)
print("𝐴𝐵 − 𝐵𝐴:")
print(c)

𝐴𝐵 − 𝐵𝐴:
[[ 4 -8]
 [12 -4]]


## Піднести матриці до степеня:
## 1) [−1; 2] [0; 1]^2

In [9]:
a = np.matrix([[-1, 2], [0, 1]])

c = np.dot(a, a)
print("A^2:")
print(c)

A^2:
[[1 0]
 [0 1]]


## Знайти добуток матриць:
## 1) [3; 5] [6; −1] ⋅ [2; 1] [−3; 2];

In [10]:
a = np.matrix([[3, 5], [6, -1]])
b = np.matrix([[2, 1], [-3, 2]])

c = np.dot(a, a)
print("A * B:")
print(c)

A * B:
[[39 10]
 [12 31]]


## 4. Обчислити визначники:
## 1) [2; 3; 4] [1; 0; 6] [7; 8; 9];

In [11]:
a = np.array([[2, 3, 4], [1, 0, 6], [7, 8, 9]])
a_det = np.linalg.det(a)

print("Визначник матриці:")
print(a_det.round(2))

Визначник матриці:
35.0


## 5. Обчислити визначники.
## 1) [1; 2; 3; 4] [-2; 1; -4; 3] [3; -4; -1; 2] [4; 3; -2; -1];

In [12]:
a = np.array([[1, 2, 3, 4], [-2, 1, -4, 3], [3, -4, -1, 2], [4, 3, -2, -1]])
a_det = np.linalg.det(a)

print("Визначник матриці:")
print(a_det.round(2))

Визначник матриці:
900.0


## 6. Знайти обернену матрицю до матриць:
## 1) [1; 2; -3] [0; 1; 2] [0; 0; 1];

In [13]:
a = np.matrix([[1, 2, -3], [0, 1, 2], [0, 0, 1]])
a_inv = np.linalg.inv(a)

print("Обернена матриця:")
print(a_inv)

Обернена матриця:
[[ 1. -2.  7.]
 [ 0.  1. -2.]
 [ 0.  0.  1.]]


## 7. Визначити ранг матриці:
## 1) [1; 2; 3; 4] [3; -1; 2; 5] [1; 2; 3; 4] [1; 3; 4; 5];

In [14]:
a = np.array([[1, 2, 3, 4], [3, 1, 2, 5], [1, 2, 3, 4], [1, 3, 4, 5]])
rank = np.linalg.matrix_rank(a)

print("Ранг матриці:")
print(rank)

Ранг матриці:
3


## 8. Розв’язати систему лінійних рівнянь методом Крамера, матричним
## методом (тобто обчислити обернену матрицю) і м. Гауса. Потім
## зробити перевірку за допомогою solve() пакету linalg :
## 22) x - 4y = -5
##     2x - 3y + z = -7
##     x + 4y + 2z = -1

In [15]:
def matrix_method(coefficients, constants):
    inverse_matrix = np.linalg.inv(coefficients)
    return np.dot(inverse_matrix, constants)

# Метод Крамера
def cramer_method(coefficients, constants):
    det_coefficients = np.linalg.det(coefficients)
    solutions = []
    for i in range(len(coefficients)):
        modified_coefficients = np.copy(coefficients)
        modified_coefficients[:, i] = constants
        solutions.append(round(np.linalg.det(modified_coefficients) / det_coefficients, 1))  # Округлюємо до десятих
    return solutions

#Метод Гауса

def gauss_method(a, b):
    n = len(b)

    for k in range(0, n-1):
        for i in range(k+1, n):
            if a[i, k] != 0.0:
                lam = a[i, k] / a[k, k]
                a[i, k+1:n] = a[i, k+1:n] - lam * a[k, k+1:n]
                b[i] = b[i] - lam * b[k]

    x = np.zeros(n)
    for k in range(n-1, -1, -1):
        x[k] = (b[k] - np.dot(a[k, k+1:n], x[k+1:n])) / a[k, k]

    return x

def main():
    a = np.array([[1.0, -4.0, 0.0],
                  [2.0, -3.0, -1.0],
                  [1.0, 4.0, 2.0]])

    b = np.array([-5.0, -7.0, -1.0])

    # Матричний метод
    x_matrix = matrix_method(a, b)
    print("Матричний метод:", x_matrix)

    # Метод Крамера
    x_cramer = cramer_method(a, b)
    print("Метод Крамера:", x_cramer)

    # Метод Гауса
    x_gauss = gauss_method(a, b)
    print("Метод Гауса:", x_gauss)


if __name__ == "__main__":
    main()

Матричний метод: [-2.77777778  0.55555556 -0.22222222]
Метод Крамера: [-2.8, 0.6, -0.2]
Метод Гауса: [-2.77777778  0.55555556 -0.22222222]


In [16]:
import numpy as np
from numpy.linalg import solve

a = np.array([[1.0, -4.0, 0.0],
                  [2.0, -3.0, -1.0],
                  [1.0, 4.0, 2.0]])

b = np.array([-5.0, -7.0, -1.0])

x = solve(a,b)

for i in range(len(x)):
    print(x[i])

-2.7777777777777777
0.5555555555555555
-0.22222222222222215


## 1) Створіть прямокутну матрицю A, яка має N рядків і M стовпців з
## випадковими елементами. Знайдіть найменший стовпчастий елемент матриці
## A, для якого сума абсолютних значень елементів максимальна.

In [18]:
import numpy as np

N = 4
M = 4

A = np.random.randint(-100, 100, size=(N, M))
print("Матриця A:")
print(A)

col_sums = np.sum(np.abs(A), axis=0)

max_sum_col_index = np.argmax(col_sums)

min_element_in_max_sum_col = np.min(A[:, max_sum_col_index])

print(f"Найменший елемент у стовпці {max_sum_col_index + 1}, для якого сума абсолютних значень максимальна: {min_element_in_max_sum_col}")


Матриця A:
[[ 50  66  95 -49]
 [-71 -37  61  65]
 [ 81  38  80 -20]
 [-60  85  67 -42]]
Найменший елемент у стовпці 3, для якого сума абсолютних значень максимальна: 61
